version: "3"

services:
  rest-tokenizer:
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: rest-tokenizer
    depends_on: 
      rest-userdic:
        condition: service_healthy
    environment:
    - USERDIC_SERVER_URL=http://rest-userdic:8080/nouns
  rest-userdic:
    build: .
    ports:
      - "8000:8080"
    command: rest-userdic
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nouns"]
      interval: 10s
      timeout: 5s
      retries: 5
