userdic:
  replicas: 1
  image: song9446/rest-lemmatizer:0.2.11
  logLevel: WARN
  persistent:
    enabled: true
    storage: 10Gi
  config:
    uniqueSuffixesCountThreshold: 5.0
    countThreshold: 30
    nounProbabilityThreshold: 0.9
tokenizer:
  replicas: 1
  image: song9446/rest-lemmatizer:0.2.11
  logLevel: WARN
  ingress:
    enabled: False
    annotations: {}
    hosts: 
    - host: example.local
      paths: ['/']
    tls: []
storageClass:
  enabled: false
  provisioner: kubernetes.io/aws-ebs
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    fsType: ext4
    type: gp2
