userdic:
  replicas: 1
  image: song9446/rest-lemmatizer:0.2.10
  logLevel: WARN
  persistent:
    enabled: true
    storage: 10Gi
  config:
    uniqueSuffixesCountThreshold: 5.0
    countThreshold: 30
    nounProbabilityThreshold: 0.9
tokenizer:
  replicas: 1
  image: song9446/rest-lemmatizer:0.2.10
  logLevel: WARN
  ingress:
    enabled: False
    annotations: {}
    hosts: 
    - host: example.local
      paths: ['/']
    tls: []
